// Sample worker data with prices and descriptions
const workers = [
  {
    id: 1,
    name: "Jane Doe",
    location: "Calgary, AB",
    services: ["Cleaning", "Laundry"],
    rating: 4.5,
    availability: ["Monday", "Wednesday", "Friday"],
    preferences: ["Eco-friendly Products", "Pet-friendly", "Child-friendly", "Own Equipment"],
    price: 25.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Jane has over 5 years of experience in housekeeping, specializing in eco-friendly cleaning methods. She loves pets and is great with kids, making her perfect for family homes."
  },
  {
    id: 2,
    name: "John Smith",
    location: "Calgary, AB",
    services: ["Organizing", "Deep Cleaning"],
    rating: 4.8,
    availability: ["Tuesday", "Thursday"],
    preferences: ["Own Equipment", "Allergy-aware"],
    price: 30.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "John is a detail-oriented cleaner with a knack for organizing spaces. He brings his own equipment and excels in allergy-sensitive environments."
  },
  {
    id: 3,
    name: "Emily Johnson",
    location: "Toronto, ON",
    services: ["Cleaning", "Organizing"],
    rating: 4.2,
    availability: ["Monday", "Saturday"],
    preferences: ["Eco-friendly Products", "Child-friendly", "Own Equipment"],
    price: 28.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Emily is passionate about creating tidy, welcoming spaces. She uses eco-friendly products and is great with children, offering weekend availability."
  },
  {
    id: 4,
    name: "Michael Brown",
    location: "Vancouver, BC",
    services: ["Laundry", "Deep Cleaning"],
    rating: 4.7,
    availability: ["Wednesday", "Sunday"],
    preferences: ["Pet-friendly", "Allergy-aware", "Own Equipment"],
    price: 35.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Michael is a reliable cleaner with expertise in deep cleaning and laundry services. He is pet-friendly and takes extra care in allergy-prone homes."
  },
  {
    id: 5,
    name: "Sarah Lee",
    location: "Calgary, AB",
    services: ["Cleaning", "Laundry", "Organizing"],
    rating: 4.9,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    preferences: ["Eco-friendly Products", "Own Equipment", "Child-friendly"],
    price: 40.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Sarah is a top-rated professional with a passion for eco-friendly cleaning. She brings her own equipment and is known for her friendly, child-safe approach."
  },
  {
    id: 6,
    name: "David Wilson",
    location: "Edmonton, AB",
    services: ["Deep Cleaning", "Laundry"],
    rating: 4.3,
    availability: ["Saturday", "Sunday"],
    preferences: ["Own Equipment", "Allergy-aware"],
    price: 32.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "David specializes in weekend deep cleaning and laundry services. He is allergy-aware and always brings his own high-quality equipment."
  },
  {
    id: 7,
    name: "Laura Martinez",
    location: "Calgary, AB",
    services: ["Cleaning", "Organizing"],
    rating: 4.6,
    availability: ["Monday", "Wednesday", "Friday"],
    preferences: ["Eco-friendly Products", "Pet-friendly", "Child-friendly", "Own Equipment"],
    price: 27.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Laura is an experienced cleaner who loves working in pet-friendly homes. She uses eco-friendly products and is great with children."
  },
  {
    id: 8,
    name: "James Anderson",
    location: "Toronto, ON",
    services: ["Laundry", "Deep Cleaning"],
    rating: 4.4,
    availability: ["Tuesday", "Thursday"],
    preferences: ["Own Equipment", "Allergy-aware"],
    price: 29.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "James is a meticulous cleaner with a focus on deep cleaning and laundry. He is allergy-aware and always brings his own equipment."
  },
  {
    id: 9,
    name: "Olivia Taylor",
    location: "Vancouver, BC",
    services: ["Cleaning", "Organizing", "Laundry"],
    rating: 4.7,
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    preferences: ["Eco-friendly Products", "Pet-friendly", "Child-friendly", "Own Equipment"],
    price: 33.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Olivia is a versatile cleaner with a passion for eco-friendly products. She is pet-friendly and great with kids, making her ideal for busy households."
  },
  {
    id: 10,
    name: "William Thomas",
    location: "Calgary, AB",
    services: ["Deep Cleaning"],
    rating: 4.1,
    availability: ["Thursday", "Friday"],
    preferences: ["Own Equipment", "Allergy-aware"],
    price: 22.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "William is an affordable deep cleaning specialist. He brings his own equipment and is experienced in allergy-sensitive cleaning."
  },
  {
    id: 11,
    name: "Sophia White",
    location: "Edmonton, AB",
    services: ["Cleaning", "Laundry"],
    rating: 4.5,
    availability: ["Monday", "Tuesday", "Wednesday"],
    preferences: ["Eco-friendly Products", "Child-friendly", "Own Equipment"],
    price: 26.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Sophia is a friendly cleaner who uses eco-friendly products. She is great with children and offers flexible weekday availability."
  },
  {
    id: 12,
    name: "Daniel Harris",
    location: "Toronto, ON",
    services: ["Organizing", "Deep Cleaning"],
    rating: 4.8,
    availability: ["Saturday", "Sunday"],
    preferences: ["Pet-friendly", "Allergy-aware"],
    price: 34.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Daniel is a weekend warrior with a talent for organizing and deep cleaning. He is pet-friendly and allergy-aware, ensuring a safe environment."
  },
  {
    id: 13,
    name: "Isabella Clark",
    location: "Vancouver, BC",
    services: ["Cleaning", "Laundry", "Organizing"],
    rating: 4.6,
    availability: ["Tuesday", "Thursday", "Saturday"],
    preferences: ["Eco-friendly Products", "Own Equipment", "Child-friendly"],
    price: 31.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Isabella is a versatile cleaner who brings her own eco-friendly equipment. She is great with kids and offers a range of services."
  },
  {
    id: 14,
    name: "Matthew Lewis",
    location: "Calgary, AB",
    services: ["Deep Cleaning", "Laundry"],
    rating: 4.3,
    availability: ["Wednesday", "Friday"],
    preferences: ["Pet-friendly", "Allergy-aware", "Own Equipment"],
    price: 28.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Matthew is a reliable cleaner with a focus on deep cleaning and laundry. He is pet-friendly and takes extra care in allergy-prone homes."
  },
  {
    id: 15,
    name: "Ava Walker",
    location: "Edmonton, AB",
    services: ["Cleaning", "Organizing"],
    rating: 4.9,
    availability: ["Monday", "Thursday", "Sunday"],
    preferences: ["Eco-friendly Products", "Own Equipment", "Child-friendly"],
    price: 36.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Ava is a top-rated cleaner with a passion for eco-friendly organizing. She brings her own equipment and is great with children."
  },
  {
    id: 16,
    name: "Ethan Hall",
    location: "Toronto, ON",
    services: ["Laundry", "Deep Cleaning"],
    rating: 4.2,
    availability: ["Tuesday", "Friday"],
    preferences: ["Own Equipment", "Allergy-aware"],
    price: 24.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Ethan is an affordable cleaner with a focus on laundry and deep cleaning. He brings his own equipment and is allergy-aware."
  },
  {
    id: 17,
    name: "Mia Young",
    location: "Vancouver, BC",
    services: ["Cleaning", "Organizing", "Laundry"],
    rating: 4.7,
    availability: ["Monday", "Wednesday", "Saturday"],
    preferences: ["Eco-friendly Products", "Pet-friendly", "Child-friendly", "Own Equipment"],
    price: 32.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Mia is a versatile cleaner with a passion for eco-friendly products. She is pet-friendly and great with kids, making her ideal for family homes."
  },
  {
    id: 18,
    name: "Alexander King",
    location: "Calgary, AB",
    services: ["Deep Cleaning"],
    rating: 4.4,
    availability: ["Thursday", "Sunday"],
    preferences: ["Own Equipment", "Allergy-aware"],
    price: 27.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Alexander is a deep cleaning specialist with a focus on allergy-sensitive environments. He brings his own equipment and offers weekend availability."
  },
  {
    id: 19,
    name: "Charlotte Wright",
    location: "Edmonton, AB",
    services: ["Cleaning", "Laundry"],
    rating: 4.6,
    availability: ["Tuesday", "Wednesday", "Friday"],
    preferences: ["Eco-friendly Products", "Child-friendly", "Own Equipment"],
    price: 29.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Charlotte is a friendly cleaner who uses eco-friendly products. She is great with children and offers flexible weekday availability."
  },
  {
    id: 20,
    name: "Lucas Green",
    location: "Montreal, QC",
    services: ["Cleaning", "Organizing"],
    rating: 4.0,
    availability: ["Monday", "Thursday"],
    preferences: ["Eco-friendly Products", "Pet-friendly", "Own Equipment"],
    price: 20.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Lucas is an affordable cleaner with a passion for eco-friendly products. He is pet-friendly and offers flexible availability."
  },
  {
    id: 21,
    name: "Hannah Adams",
    location: "Ottawa, ON",
    services: ["Laundry", "Deep Cleaning"],
    rating: 4.5,
    availability: ["Wednesday", "Friday", "Saturday"],
    preferences: ["Own Equipment", "Child-friendly"],
    price: 22.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Hannah is a reliable cleaner with a focus on laundry and deep cleaning. She brings her own equipment and is great with children."
  },
  {
    id: 22,
    name: "Noah Turner",
    location: "Calgary, AB",
    services: ["Cleaning", "Laundry", "Organizing"],
    rating: 4.8,
    availability: ["Tuesday", "Thursday", "Sunday"],
    preferences: ["Eco-friendly Products", "Pet-friendly", "Allergy-aware"],
    price: 38.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Noah is a top-rated cleaner with a passion for eco-friendly products. He is pet-friendly and allergy-aware, offering comprehensive services."
  },
  {
    id: 23,
    name: "Zoe Scott",
    location: "Toronto, ON",
    services: ["Deep Cleaning", "Organizing"],
    rating: 4.3,
    availability: ["Monday", "Wednesday"],
    preferences: ["Own Equipment", "Child-friendly"],
    price: 26.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Zoe is an affordable cleaner with a focus on deep cleaning and organizing. She brings her own equipment and is great with children."
  },
  {
    id: 24,
    name: "Mason Carter",
    location: "Vancouver, BC",
    services: ["Cleaning", "Laundry"],
    rating: 4.6,
    availability: ["Friday", "Saturday"],
    preferences: ["Pet-friendly", "Allergy-aware", "Own Equipment"],
    price: 30.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Mason is a reliable cleaner with a focus on cleaning and laundry. He is pet-friendly and allergy-aware, offering weekend availability."
  },
  {
    id: 25,
    name: "Lily Evans",
    location: "Montreal, QC",
    services: ["Organizing", "Deep Cleaning"],
    rating: 4.9,
    availability: ["Tuesday", "Thursday", "Sunday"],
    preferences: ["Eco-friendly Products", "Own Equipment", "Child-friendly"],
    price: 45.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Lily is a top-rated cleaner with a passion for eco-friendly organizing and deep cleaning. She brings her own equipment and is great with children."
  },
  {
    id: 26,
    name: "Ella Thompson",
    location: "Ottawa, ON",
    services: ["Cleaning"],
    rating: 2.5,
    availability: ["Monday", "Tuesday"],
    preferences: ["Own Equipment"],
    price: 15.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Ella is an affordable cleaner with a focus on basic cleaning services. She brings her own equipment but has received mixed reviews for her work."
  },
  {
    id: 27,
    name: "Liam Wilson",
    location: "Calgary, AB",
    services: ["Laundry"],
    rating: 3.0,
    availability: ["Wednesday", "Thursday"],
    preferences: ["Pet-friendly", "Own Equipment"],
    price: 16.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Liam is an affordable laundry specialist who is pet-friendly. He has received average reviews for his services."
  },
  {
    id: 28,
    name: "Grace Lee",
    location: "Toronto, ON",
    services: ["Organizing"],
    rating: 2.8,
    availability: ["Friday", "Saturday"],
    preferences: ["Eco-friendly Products", "Own Equipment"],
    price: 17.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Grace is an affordable organizer with a passion for eco-friendly products. She has received mixed reviews for her work."
  },
  {
    id: 29,
    name: "Benjamin Clark",
    location: "Vancouver, BC",
    services: ["Deep Cleaning"],
    rating: 3.2,
    availability: ["Sunday"],
    preferences: ["Allergy-aware", "Own Equipment"],
    price: 18.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Benjamin is an affordable deep cleaning specialist who is allergy-aware. He has received average reviews for his services."
  },
  {
    id: 30,
    name: "Amelia Walker",
    location: "Edmonton, AB",
    services: ["Cleaning", "Laundry"],
    rating: 3.5,
    availability: ["Monday", "Wednesday"],
    preferences: ["Child-friendly"],
    price: 19.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Amelia is an affordable cleaner with a focus on cleaning and laundry. She is great with children but has received average reviews."
  },
  {
    id: 31,
    name: "Henry Harris",
    location: "Montreal, QC",
    services: ["Organizing", "Deep Cleaning"],
    rating: 3.8,
    availability: ["Tuesday", "Thursday"],
    preferences: ["Own Equipment", "Pet-friendly"],
    price: 20.00,
    photo: "https://img.freepik.com/premium-photo/teacher-with-beauty-smiling-face-stands-white-background_653449-23603.jpg",
    description: "Henry is an affordable organizer and deep cleaner who brings his own equipment. He is pet-friendly and has received average reviews."
  },
  {
    id: 32,
    name: "Chloe Young",
    location: "Ottawa, ON",
    services: ["Cleaning", "Organizing"],
    rating: 4.0,
    availability: ["Friday", "Saturday", "Sunday"],
    preferences: ["Eco-friendly Products", "Child-friendly"],
    price: 21.00,
    photo: "https://img.freepik.com/premium-photo/portrait-business-woman_980226-8965.jpg",
    description: "Chloe is an affordable cleaner with a passion for eco-friendly products. She is great with children and offers weekend availability."
  }
];